import type { Metadata } from "next";
import "./globals.css";
import { montserrat } from "@/app/fonts";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${montserrat.className}`}>
        <Toaster />
        {children}
      </body>
    </html>
  );
}
