// This file is auto-generated by @hey-api/openapi-ts

export type DocumentResponse = {
  document_id?: number;
  raw_text?: string;
  patient_id?: number;
  hl7_fhir_data?: {
    [key: string]: unknown;
  };
};

export type ChatResponse = {
  chat_id?: number;
  organisation?: OrganisationResponse;
  patient?: UserResponse;
  guardian?: UserResponse | null;
};

export type MessageResponse = {
  message_id?: number;
  author?: UserResponse;
  chat_id?: number;
  is_organisation_message?: boolean;
  text?: string;
};

export type ChatSuggestionResponse = {
  hash?: string;
  text?: string;
};

export type PatientDatasetItemResponse = {
  hash?: string;
  summary?: string;
  sources?: Array<DocumentResponse>;
};

export type OrganisationResponse = {
  organisation_id?: number;
  name?: string;
  address?: string;
  logo?: FileUploadResponse;
  hospital?: HospitalResponse;
};

export type UserResponse = {
  user_id?: number;
  name?: string;
  email?: string;
};

export type FileUploadResponse = {
  file_upload_id?: number;
  asset_location?: string;
};

export type HospitalResponse = {
  hospital_id?: number;
  name?: string;
  address?: string;
  logo?: FileUploadResponse;
};

export type LoginData = {
  body: {
    email: string;
    password: string;
  };
};

export type LoginResponse = unknown;

export type LoginError = unknown;

export type RegisterData = {
  body: {
    name: string;
    email: string;
    password: string;
    password_confirmation?: string;
  };
};

export type RegisterResponse = unknown;

export type RegisterError = unknown;

export type ChatIndexResponse = Array<ChatResponse>;

export type ChatIndexError = unknown;

export type ChatStoreData = {
  body: {
    organisation_id: number;
    /**
     * Id of a patient I am representing i.e. my child
     */
    ward_id?: number;
  };
};

export type ChatStoreResponse = ChatResponse;

export type ChatStoreError = unknown;

export type ChatShowData = {
  path?: {
    chatId?: unknown;
  };
};

export type ChatShowResponse = ChatResponse;

export type ChatShowError = unknown;

export type ChatIndexMessagedData = {
  path?: {
    chatId?: unknown;
  };
};

export type ChatIndexMessagedResponse = Array<MessageResponse>;

export type ChatIndexMessagedError = unknown;

export type ChatStoreMessageData = {
  body: {
    text: string;
  };
  path?: {
    chatId?: unknown;
  };
};

export type ChatStoreMessageResponse = MessageResponse;

export type ChatStoreMessageError = unknown;

export type ChatIndexSuggestionsData = {
  path?: {
    chatId?: unknown;
  };
};

export type ChatIndexSuggestionsResponse = Array<ChatSuggestionResponse>;

export type ChatIndexSuggestionsError = unknown;

export type ChatIndexPatientDatasetData = {
  path?: {
    chatId?: unknown;
  };
};

export type ChatIndexPatientDatasetResponse = Array<PatientDatasetItemResponse>;

export type ChatIndexPatientDatasetError = unknown;

export type DocumentIndexData = {
  query?: {
    /**
     * Id of the organisation for which I want to list documents for
     */
    organisation_id?: number;
    /**
     * Id of the patient for which I want to list documents for
     */
    patient_id?: number;
  };
};

export type DocumentIndexResponse = Array<DocumentResponse>;

export type DocumentIndexError = unknown;

export type DocumentStoreData = {
  body: {
    document?: Blob | File;
  };
};

export type DocumentStoreResponse = DocumentResponse;

export type DocumentStoreError = unknown;

export type DocumentShowData = {
  path?: {
    documentId?: unknown;
  };
};

export type DocumentShowResponse = DocumentResponse;

export type DocumentShowError = unknown;

export type MeIndexWardsResponse = Array<UserResponse>;

export type MeIndexWardsError = unknown;

export type OrganisationIndexResponse = Array<OrganisationResponse>;

export type OrganisationIndexError = unknown;

export type OrganisationShowData = {
  path?: {
    organisationId?: unknown;
  };
};

export type OrganisationShowResponse = OrganisationResponse;

export type OrganisationShowError = unknown;

export type OrganisationIndexPatientsData = {
  path?: {
    organisationId?: unknown;
  };
};

export type OrganisationIndexPatientsResponse = Array<UserResponse>;

export type OrganisationIndexPatientsError = unknown;
